[package]
name = "starter-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3"
config = "0.13"
tokio = { version = "1.29", features = ["rt-multi-thread", "macros"] }

